spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    discovery:
      client:
        simple:
          instances:
            order[0]:
              uri: "http://localhost:8082"
server:
  port: 8081
